"""esquema inicial

Revision ID: a6dc612735e8
Revises: 
Create Date: 2026-06-28 13:28:42.754925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6dc612735e8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalogo_planes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clave', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('short_label', sa.String(length=32), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('precio_mensual', sa.Float(), nullable=False),
    sa.Column('precio_anual', sa.Float(), nullable=True),
    sa.Column('max_usuarios', sa.Integer(), nullable=True),
    sa.Column('max_activos', sa.Integer(), nullable=True),
    sa.Column('storage_mb', sa.Integer(), nullable=True),
    sa.Column('soporte', sa.String(length=40), nullable=True),
    sa.Column('visible_registro', sa.Boolean(), nullable=False),
    sa.Column('destacado', sa.Boolean(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('caracteristicas_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('catalogo_planes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_catalogo_planes_clave'), ['clave'], unique=True)

    op.create_table('empresas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('razon_social', sa.String(length=200), nullable=False),
    sa.Column('nit', sa.String(length=32), nullable=True),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('ciudad', sa.String(length=120), nullable=True),
    sa.Column('pais', sa.String(length=120), nullable=True),
    sa.Column('sector', sa.String(length=32), nullable=True),
    sa.Column('slug', sa.String(length=48), nullable=True),
    sa.Column('logo', sa.String(length=255), nullable=True),
    sa.Column('telefono', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('moneda', sa.String(length=8), nullable=True),
    sa.Column('monedas_activas_json', sa.Text(), nullable=True),
    sa.Column('zona_horaria', sa.String(length=64), nullable=True),
    sa.Column('jornada_habilitada', sa.Boolean(), nullable=True),
    sa.Column('jornada_hora_inicio', sa.String(length=5), nullable=True),
    sa.Column('jornada_hora_fin', sa.String(length=5), nullable=True),
    sa.Column('jornada_dias', sa.String(length=32), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.Column('suspendida', sa.Boolean(), nullable=False),
    sa.Column('modulos_activos_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_empresas_slug'), ['slug'], unique=True)

    op.create_table('reglas_plataforma',
    sa.Column('clave', sa.String(length=64), nullable=False),
    sa.Column('valor', sa.String(length=255), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('clave')
    )
    op.create_table('sectores_catalogo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clave', sa.String(length=32), nullable=False),
    sa.Column('etiqueta', sa.String(length=120), nullable=False),
    sa.Column('visible_registro', sa.Boolean(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sectores_catalogo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sectores_catalogo_clave'), ['clave'], unique=True)

    op.create_table('inv_clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('documento', sa.String(length=32), nullable=True),
    sa.Column('telefono', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inv_clientes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inv_clientes_empresa_id'), ['empresa_id'], unique=False)

    op.create_table('inv_productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('marca', sa.String(length=120), nullable=True),
    sa.Column('categoria', sa.String(length=120), nullable=True),
    sa.Column('imagen', sa.String(length=255), nullable=True),
    sa.Column('unidad', sa.String(length=32), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('stock_minimo', sa.Integer(), nullable=False),
    sa.Column('precio_compra', sa.Float(), nullable=True),
    sa.Column('precio_venta', sa.Float(), nullable=True),
    sa.Column('precios_json', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'sku', name='uq_inv_producto_empresa_sku')
    )
    with op.batch_alter_table('inv_productos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inv_productos_empresa_id'), ['empresa_id'], unique=False)

    op.create_table('inv_proveedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('nit', sa.String(length=32), nullable=True),
    sa.Column('contacto_nombre', sa.String(length=200), nullable=True),
    sa.Column('contacto_email', sa.String(length=120), nullable=True),
    sa.Column('contacto_telefono', sa.String(length=40), nullable=True),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inv_proveedores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inv_proveedores_empresa_id'), ['empresa_id'], unique=False)

    op.create_table('machine_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('clave', sa.String(length=48), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('prefijo', sa.String(length=8), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.Column('sector_industrial', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prefijo')
    )
    with op.batch_alter_table('machine_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_machine_types_clave'), ['clave'], unique=False)
        batch_op.create_index(batch_op.f('ix_machine_types_empresa_id'), ['empresa_id'], unique=False)

    op.create_table('planes_suscripcion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('plan', sa.String(length=32), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('estado_ciclo', sa.String(length=16), nullable=True),
    sa.Column('pasarela_customer_id', sa.String(length=120), nullable=True),
    sa.Column('pasarela_subscription_id', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plantillas_dashboard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('sector', sa.String(length=32), nullable=False),
    sa.Column('config_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id')
    )
    op.create_table('proveedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('nit', sa.String(length=32), nullable=True),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('contacto_nombre', sa.String(length=200), nullable=True),
    sa.Column('contacto_cargo', sa.String(length=120), nullable=True),
    sa.Column('contacto_email', sa.String(length=120), nullable=True),
    sa.Column('contacto_telefono', sa.String(length=40), nullable=True),
    sa.Column('tipo', sa.String(length=16), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('proveedores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_proveedores_empresa_id'), ['empresa_id'], unique=False)

    op.create_table('sedes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('es_principal', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spare_parts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('categoria', sa.String(length=120), nullable=True),
    sa.Column('unidad', sa.String(length=32), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.Column('stock_minimo', sa.Integer(), nullable=True),
    sa.Column('ubicacion_almacen', sa.String(length=120), nullable=True),
    sa.Column('costo_unitario', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    with op.batch_alter_table('spare_parts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_spare_parts_empresa_id'), ['empresa_id'], unique=False)

    op.create_table('campos_personalizados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('sector', sa.String(length=32), nullable=False),
    sa.Column('entidad', sa.String(length=16), nullable=False),
    sa.Column('machine_type_id', sa.Integer(), nullable=True),
    sa.Column('categorias_ids', sa.Text(), nullable=True),
    sa.Column('clave', sa.String(length=64), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('seccion', sa.String(length=80), nullable=True),
    sa.Column('seccion_ancla', sa.String(length=32), nullable=True),
    sa.Column('tipo', sa.String(length=16), nullable=True),
    sa.Column('texto_tamano', sa.String(length=16), nullable=True),
    sa.Column('opciones', sa.Text(), nullable=True),
    sa.Column('obligatorio', sa.Boolean(), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['machine_type_id'], ['machine_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campos_personalizados', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campos_personalizados_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campos_personalizados_entidad'), ['entidad'], unique=False)
        batch_op.create_index(batch_op.f('ix_campos_personalizados_seccion'), ['seccion'], unique=False)
        batch_op.create_index(batch_op.f('ix_campos_personalizados_sector'), ['sector'], unique=False)

    op.create_table('facturas_empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('suscripcion_id', sa.Integer(), nullable=True),
    sa.Column('numero', sa.String(length=32), nullable=False),
    sa.Column('concepto', sa.String(length=200), nullable=True),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('moneda', sa.String(length=8), nullable=True),
    sa.Column('periodo', sa.String(length=7), nullable=True),
    sa.Column('estado', sa.String(length=16), nullable=True),
    sa.Column('fecha_emision', sa.Date(), nullable=False),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=True),
    sa.Column('fecha_pago', sa.Date(), nullable=True),
    sa.Column('metodo_pago', sa.String(length=64), nullable=True),
    sa.Column('referencia_pago', sa.String(length=120), nullable=True),
    sa.Column('pasarela_payment_id', sa.String(length=120), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['suscripcion_id'], ['planes_suscripcion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('facturas_empresa', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_facturas_empresa_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_facturas_empresa_periodo'), ['periodo'], unique=False)
        batch_op.create_index(batch_op.f('ix_facturas_empresa_suscripcion_id'), ['suscripcion_id'], unique=False)

    op.create_table('inv_compras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=True),
    sa.Column('numero', sa.String(length=32), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['proveedor_id'], ['inv_proveedores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inv_compras', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inv_compras_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inv_compras_proveedor_id'), ['proveedor_id'], unique=False)

    op.create_table('inv_ventas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('numero', sa.String(length=32), nullable=True),
    sa.Column('moneda', sa.String(length=8), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('forma_pago', sa.String(length=16), nullable=True),
    sa.Column('estado_cobro', sa.String(length=16), nullable=True),
    sa.Column('monto_cobrado', sa.Float(), nullable=True),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['inv_clientes.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inv_ventas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inv_ventas_cliente_id'), ['cliente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inv_ventas_empresa_id'), ['empresa_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('nombre_visible', sa.String(length=120), nullable=True),
    sa.Column('telefono', sa.String(length=40), nullable=True),
    sa.Column('area', sa.String(length=120), nullable=True),
    sa.Column('sede_id', sa.Integer(), nullable=True),
    sa.Column('rol', sa.String(length=32), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('bloqueado', sa.Boolean(), nullable=False),
    sa.Column('bloqueado_en', sa.DateTime(), nullable=True),
    sa.Column('onboarding_completado', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['sede_id'], ['sedes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'username', name='uq_user_empresa_username')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_sede_id'), ['sede_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=False)

    op.create_table('inv_compra_lineas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('compra_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('marca', sa.String(length=120), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Float(), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['compra_id'], ['inv_compras.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['inv_productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inv_compra_lineas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inv_compra_lineas_compra_id'), ['compra_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inv_compra_lineas_producto_id'), ['producto_id'], unique=False)

    op.create_table('inv_venta_cobros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venta_id', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['venta_id'], ['inv_ventas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inv_venta_cobros', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inv_venta_cobros_venta_id'), ['venta_id'], unique=False)

    op.create_table('inv_venta_lineas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venta_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Float(), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['producto_id'], ['inv_productos.id'], ),
    sa.ForeignKeyConstraint(['venta_id'], ['inv_ventas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inv_venta_lineas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inv_venta_lineas_producto_id'), ['producto_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inv_venta_lineas_venta_id'), ['venta_id'], unique=False)

    op.create_table('platform_audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('accion', sa.String(length=32), nullable=False),
    sa.Column('actor_label', sa.String(length=120), nullable=False),
    sa.Column('detalle', sa.String(length=500), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('visible_cliente', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('platform_audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_platform_audit_log_accion'), ['accion'], unique=False)
        batch_op.create_index(batch_op.f('ix_platform_audit_log_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_platform_audit_log_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_platform_audit_log_user_id'), ['user_id'], unique=False)

    op.create_table('technicians',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('especialidad', sa.String(length=120), nullable=True),
    sa.Column('telefono', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('technicians', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_technicians_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_technicians_user_id'), ['user_id'], unique=True)

    op.create_table('tenant_activity_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('tipo', sa.String(length=32), nullable=False),
    sa.Column('detalle', sa.String(length=500), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tenant_activity_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenant_activity_log_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_tenant_activity_log_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tenant_activity_log_tipo'), ['tipo'], unique=False)
        batch_op.create_index(batch_op.f('ix_tenant_activity_log_user_id'), ['user_id'], unique=False)

    op.create_table('usuario_campo_valores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('campo_id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['campo_id'], ['campos_personalizados.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'campo_id', name='uq_usuario_campo')
    )
    with op.batch_alter_table('usuario_campo_valores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuario_campo_valores_campo_id'), ['campo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_usuario_campo_valores_user_id'), ['user_id'], unique=False)

    op.create_table('machines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('sede_id', sa.Integer(), nullable=True),
    sa.Column('parent_machine_id', sa.Integer(), nullable=True),
    sa.Column('codigo', sa.String(length=64), nullable=False),
    sa.Column('machine_type_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('registro_tipo', sa.String(length=32), nullable=True),
    sa.Column('checklist_registro', sa.Text(), nullable=True),
    sa.Column('etiquetas', sa.Text(), nullable=True),
    sa.Column('ubicacion', sa.String(length=200), nullable=True),
    sa.Column('area', sa.String(length=120), nullable=True),
    sa.Column('marca', sa.String(length=120), nullable=True),
    sa.Column('modelo', sa.String(length=120), nullable=True),
    sa.Column('fabricante', sa.String(length=120), nullable=True),
    sa.Column('numero_serie', sa.String(length=120), nullable=True),
    sa.Column('fecha_fabricacion', sa.Date(), nullable=True),
    sa.Column('fecha_ingreso', sa.Date(), nullable=True),
    sa.Column('criticidad', sa.String(length=32), nullable=True),
    sa.Column('fecha_instalacion', sa.Date(), nullable=True),
    sa.Column('fecha_puesta_marcha', sa.Date(), nullable=True),
    sa.Column('vida_util_anios', sa.Integer(), nullable=True),
    sa.Column('horas_operacion', sa.Float(), nullable=True),
    sa.Column('fecha_compra', sa.Date(), nullable=True),
    sa.Column('valor_compra', sa.Float(), nullable=True),
    sa.Column('moneda_compra', sa.String(length=8), nullable=True),
    sa.Column('proveedor', sa.String(length=200), nullable=True),
    sa.Column('tiempo_garantia_meses', sa.Integer(), nullable=True),
    sa.Column('garantia_hasta', sa.Date(), nullable=True),
    sa.Column('manual_url', sa.String(length=500), nullable=True),
    sa.Column('ficha_tecnica_url', sa.String(length=500), nullable=True),
    sa.Column('foto_url', sa.String(length=500), nullable=True),
    sa.Column('requiere_mantenimiento', sa.Boolean(), nullable=True),
    sa.Column('tipos_mantenimiento', sa.Text(), nullable=True),
    sa.Column('frecuencia_mantenimiento', sa.String(length=32), nullable=True),
    sa.Column('responsable_technician_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('es_critico', sa.Boolean(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['machine_type_id'], ['machine_types.id'], ),
    sa.ForeignKeyConstraint(['parent_machine_id'], ['machines.id'], ),
    sa.ForeignKeyConstraint(['responsable_technician_id'], ['technicians.id'], ),
    sa.ForeignKeyConstraint(['sede_id'], ['sedes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    with op.batch_alter_table('machines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_machines_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_machines_parent_machine_id'), ['parent_machine_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_machines_responsable_technician_id'), ['responsable_technician_id'], unique=False)

    op.create_table('activo_campo_valores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('campo_id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['campo_id'], ['campos_personalizados.id'], ),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('machine_id', 'campo_id', name='uq_activo_campo')
    )
    with op.batch_alter_table('activo_campo_valores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activo_campo_valores_campo_id'), ['campo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activo_campo_valores_machine_id'), ['machine_id'], unique=False)

    op.create_table('machine_monthly_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('horas_meta', sa.Float(), nullable=True),
    sa.Column('guardado_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('machine_id', 'anio', 'mes', name='uq_machine_plan_mes')
    )
    with op.batch_alter_table('machine_monthly_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_machine_monthly_plans_anio'), ['anio'], unique=False)
        batch_op.create_index(batch_op.f('ix_machine_monthly_plans_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_machine_monthly_plans_machine_id'), ['machine_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_machine_monthly_plans_mes'), ['mes'], unique=False)

    op.create_table('preventive_maintenance_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('actividad', sa.String(length=200), nullable=False),
    sa.Column('actividad_key', sa.String(length=220), nullable=False),
    sa.Column('frecuencia_valor', sa.Integer(), nullable=False),
    sa.Column('frecuencia_unidad', sa.String(length=16), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('machine_id', 'actividad_key', name='uq_prev_plan_machine_actividad')
    )
    with op.batch_alter_table('preventive_maintenance_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_preventive_maintenance_plans_actividad_key'), ['actividad_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_preventive_maintenance_plans_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_preventive_maintenance_plans_machine_id'), ['machine_id'], unique=False)

    op.create_table('work_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('numero', sa.String(length=32), nullable=True),
    sa.Column('folio_anio', sa.Integer(), nullable=True),
    sa.Column('folio_seq', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('tipo', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('prioridad', sa.String(length=32), nullable=True),
    sa.Column('fecha_programada', sa.Date(), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=True),
    sa.Column('fecha_cierre', sa.DateTime(), nullable=True),
    sa.Column('tiempo_gastado_minutos', sa.Integer(), nullable=True),
    sa.Column('usar_jornada_laboral', sa.Boolean(), nullable=True),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('technician_id', sa.Integer(), nullable=True),
    sa.Column('preventive_plan_id', sa.Integer(), nullable=True),
    sa.Column('frecuencia_valor', sa.Integer(), nullable=True),
    sa.Column('frecuencia_unidad', sa.String(length=16), nullable=True),
    sa.Column('ubicacion', sa.String(length=200), nullable=True),
    sa.Column('area', sa.String(length=120), nullable=True),
    sa.Column('autorizado_por', sa.String(length=120), nullable=True),
    sa.Column('recibido_por', sa.String(length=120), nullable=True),
    sa.Column('empresa_tercerizada', sa.String(length=200), nullable=True),
    sa.Column('maquina_requirio_paro', sa.Boolean(), nullable=False),
    sa.Column('ejecucion_tipo', sa.String(length=16), nullable=False),
    sa.Column('proveedor_id', sa.Integer(), nullable=True),
    sa.Column('supervisor_technician_id', sa.Integer(), nullable=True),
    sa.Column('contacto_proveedor', sa.String(length=200), nullable=True),
    sa.Column('numero_cotizacion', sa.String(length=64), nullable=True),
    sa.Column('costo_estimado', sa.Float(), nullable=True),
    sa.Column('costo_real', sa.Float(), nullable=True),
    sa.Column('proveedor_incluye_insumos', sa.Boolean(), nullable=True),
    sa.Column('fecha_limite', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.ForeignKeyConstraint(['preventive_plan_id'], ['preventive_maintenance_plans.id'], ),
    sa.ForeignKeyConstraint(['proveedor_id'], ['proveedores.id'], ),
    sa.ForeignKeyConstraint(['supervisor_technician_id'], ['technicians.id'], ),
    sa.ForeignKeyConstraint(['technician_id'], ['technicians.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('work_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_orders_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_orders_numero'), ['numero'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_orders_preventive_plan_id'), ['preventive_plan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_orders_proveedor_id'), ['proveedor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_orders_supervisor_technician_id'), ['supervisor_technician_id'], unique=False)

    op.create_table('incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=32), nullable=True),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('machine_id', sa.Integer(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('reportado_por', sa.String(length=200), nullable=True),
    sa.Column('cargo_reportante', sa.String(length=120), nullable=True),
    sa.Column('telefono_contacto', sa.String(length=40), nullable=True),
    sa.Column('area', sa.String(length=120), nullable=True),
    sa.Column('ubicacion', sa.String(length=200), nullable=True),
    sa.Column('tipo', sa.String(length=32), nullable=True),
    sa.Column('prioridad', sa.String(length=32), nullable=True),
    sa.Column('equipo_detenido', sa.Boolean(), nullable=False),
    sa.Column('fecha_evento', sa.Date(), nullable=True),
    sa.Column('hora_evento', sa.String(length=5), nullable=True),
    sa.Column('reportado_en', sa.DateTime(), nullable=True),
    sa.Column('resuelto', sa.Boolean(), nullable=True),
    sa.Column('resuelto_en', sa.DateTime(), nullable=True),
    sa.Column('resuelto_por_id', sa.Integer(), nullable=True),
    sa.Column('notas_resolucion', sa.Text(), nullable=True),
    sa.Column('work_order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.ForeignKeyConstraint(['resuelto_por_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incidents_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_numero'), ['numero'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_resuelto_por_id'), ['resuelto_por_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_incidents_work_order_id'), ['work_order_id'], unique=False)

    op.create_table('work_order_jornadas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_order_id', sa.Integer(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=False),
    sa.Column('fecha_fin', sa.DateTime(), nullable=False),
    sa.Column('technician_id', sa.Integer(), nullable=True),
    sa.Column('tecnico_nombre', sa.String(length=200), nullable=True),
    sa.Column('descripcion_avance', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['technician_id'], ['technicians.id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('work_order_jornadas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_order_jornadas_work_order_id'), ['work_order_id'], unique=False)

    op.create_table('work_order_repuestos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_order_id', sa.Integer(), nullable=False),
    sa.Column('spare_part_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('notas', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['spare_part_id'], ['spare_parts.id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('work_order_repuestos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_order_repuestos_work_order_id'), ['work_order_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_order_repuestos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_order_repuestos_work_order_id'))

    op.drop_table('work_order_repuestos')
    with op.batch_alter_table('work_order_jornadas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_order_jornadas_work_order_id'))

    op.drop_table('work_order_jornadas')
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incidents_work_order_id'))
        batch_op.drop_index(batch_op.f('ix_incidents_user_id'))
        batch_op.drop_index(batch_op.f('ix_incidents_resuelto_por_id'))
        batch_op.drop_index(batch_op.f('ix_incidents_numero'))
        batch_op.drop_index(batch_op.f('ix_incidents_empresa_id'))

    op.drop_table('incidents')
    with op.batch_alter_table('work_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_orders_supervisor_technician_id'))
        batch_op.drop_index(batch_op.f('ix_work_orders_proveedor_id'))
        batch_op.drop_index(batch_op.f('ix_work_orders_preventive_plan_id'))
        batch_op.drop_index(batch_op.f('ix_work_orders_numero'))
        batch_op.drop_index(batch_op.f('ix_work_orders_empresa_id'))

    op.drop_table('work_orders')
    with op.batch_alter_table('preventive_maintenance_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_preventive_maintenance_plans_machine_id'))
        batch_op.drop_index(batch_op.f('ix_preventive_maintenance_plans_empresa_id'))
        batch_op.drop_index(batch_op.f('ix_preventive_maintenance_plans_actividad_key'))

    op.drop_table('preventive_maintenance_plans')
    with op.batch_alter_table('machine_monthly_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_machine_monthly_plans_mes'))
        batch_op.drop_index(batch_op.f('ix_machine_monthly_plans_machine_id'))
        batch_op.drop_index(batch_op.f('ix_machine_monthly_plans_empresa_id'))
        batch_op.drop_index(batch_op.f('ix_machine_monthly_plans_anio'))

    op.drop_table('machine_monthly_plans')
    with op.batch_alter_table('activo_campo_valores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activo_campo_valores_machine_id'))
        batch_op.drop_index(batch_op.f('ix_activo_campo_valores_campo_id'))

    op.drop_table('activo_campo_valores')
    with op.batch_alter_table('machines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_machines_responsable_technician_id'))
        batch_op.drop_index(batch_op.f('ix_machines_parent_machine_id'))
        batch_op.drop_index(batch_op.f('ix_machines_empresa_id'))

    op.drop_table('machines')
    with op.batch_alter_table('usuario_campo_valores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuario_campo_valores_user_id'))
        batch_op.drop_index(batch_op.f('ix_usuario_campo_valores_campo_id'))

    op.drop_table('usuario_campo_valores')
    with op.batch_alter_table('tenant_activity_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenant_activity_log_user_id'))
        batch_op.drop_index(batch_op.f('ix_tenant_activity_log_tipo'))
        batch_op.drop_index(batch_op.f('ix_tenant_activity_log_empresa_id'))
        batch_op.drop_index(batch_op.f('ix_tenant_activity_log_created_at'))

    op.drop_table('tenant_activity_log')
    with op.batch_alter_table('technicians', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_technicians_user_id'))
        batch_op.drop_index(batch_op.f('ix_technicians_empresa_id'))

    op.drop_table('technicians')
    with op.batch_alter_table('platform_audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_platform_audit_log_user_id'))
        batch_op.drop_index(batch_op.f('ix_platform_audit_log_empresa_id'))
        batch_op.drop_index(batch_op.f('ix_platform_audit_log_created_at'))
        batch_op.drop_index(batch_op.f('ix_platform_audit_log_accion'))

    op.drop_table('platform_audit_log')
    with op.batch_alter_table('inv_venta_lineas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inv_venta_lineas_venta_id'))
        batch_op.drop_index(batch_op.f('ix_inv_venta_lineas_producto_id'))

    op.drop_table('inv_venta_lineas')
    with op.batch_alter_table('inv_venta_cobros', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inv_venta_cobros_venta_id'))

    op.drop_table('inv_venta_cobros')
    with op.batch_alter_table('inv_compra_lineas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inv_compra_lineas_producto_id'))
        batch_op.drop_index(batch_op.f('ix_inv_compra_lineas_compra_id'))

    op.drop_table('inv_compra_lineas')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_sede_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('inv_ventas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inv_ventas_empresa_id'))
        batch_op.drop_index(batch_op.f('ix_inv_ventas_cliente_id'))

    op.drop_table('inv_ventas')
    with op.batch_alter_table('inv_compras', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inv_compras_proveedor_id'))
        batch_op.drop_index(batch_op.f('ix_inv_compras_empresa_id'))

    op.drop_table('inv_compras')
    with op.batch_alter_table('facturas_empresa', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_facturas_empresa_suscripcion_id'))
        batch_op.drop_index(batch_op.f('ix_facturas_empresa_periodo'))
        batch_op.drop_index(batch_op.f('ix_facturas_empresa_empresa_id'))

    op.drop_table('facturas_empresa')
    with op.batch_alter_table('campos_personalizados', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campos_personalizados_sector'))
        batch_op.drop_index(batch_op.f('ix_campos_personalizados_seccion'))
        batch_op.drop_index(batch_op.f('ix_campos_personalizados_entidad'))
        batch_op.drop_index(batch_op.f('ix_campos_personalizados_empresa_id'))

    op.drop_table('campos_personalizados')
    with op.batch_alter_table('spare_parts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_spare_parts_empresa_id'))

    op.drop_table('spare_parts')
    op.drop_table('sedes')
    with op.batch_alter_table('proveedores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proveedores_empresa_id'))

    op.drop_table('proveedores')
    op.drop_table('plantillas_dashboard')
    op.drop_table('planes_suscripcion')
    with op.batch_alter_table('machine_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_machine_types_empresa_id'))
        batch_op.drop_index(batch_op.f('ix_machine_types_clave'))

    op.drop_table('machine_types')
    with op.batch_alter_table('inv_proveedores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inv_proveedores_empresa_id'))

    op.drop_table('inv_proveedores')
    with op.batch_alter_table('inv_productos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inv_productos_empresa_id'))

    op.drop_table('inv_productos')
    with op.batch_alter_table('inv_clientes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inv_clientes_empresa_id'))

    op.drop_table('inv_clientes')
    with op.batch_alter_table('sectores_catalogo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sectores_catalogo_clave'))

    op.drop_table('sectores_catalogo')
    op.drop_table('reglas_plataforma')
    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_empresas_slug'))

    op.drop_table('empresas')
    with op.batch_alter_table('catalogo_planes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_catalogo_planes_clave'))

    op.drop_table('catalogo_planes')
    # ### end Alembic commands ###
